server:
  port: 8081
  error:
    include-message: always

spring:
  application:
    name: user-service

  kafka:
    # Если переменная не задана, по умолчанию localhost (для запуска из IDE)
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: user-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
          # Разрешаем Jackson десериализовать классы из пакета
          spring.json.trusted.packages: "org.mychko.mytasktracker.dto,org.mychko.mytasktracker.model"

  datasource:
    # Если переменная не задана, по умолчанию localhost:54325 (для запуска из IDE)
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:54325/userdb}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:user}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}