server:
  port: 8081
  error:
    include-message: always

spring:
  application:
    name: user-service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: user-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
          # Разрешаем Jackson десериализовать классы из пакета
          spring.json.trusted.packages: "org.mychko.mytasktracker.dto,org.mychko.mytasktracker.model"

  datasource:
    url: jdbc:postgresql://localhost:54325/userdb
    username: user
    password: user

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update